version: '3'

services:
  db:
    image: postgres:latest
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"    

  app1: &app
    build: .
    hostname: app1
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "175MB"    

  app2:
    <<: *app
    hostname: app2  

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"