version: '3'

services:
  db:
    image: postgres:latest
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 5s
      retries: 10

  app1: &app
    build: .
    environment: 
      - SERVER_NAME=:3000
    network_mode: host
    depends_on:
      db:
        condition: service_healthy

  app2:
    <<: *app
    build: .
    environment: 
      - SERVER_NAME=:3001

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2