version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 3s
      timeout: 5s
      retries: 10

  app1:
    build: .
    hostname: app1
    depends_on:
      db:
        condition: service_healthy

  app2:
    <<: *app1  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"  

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1              