version: '3'

services:
  db:
    image: postgres:latest
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"    

  pgbouncer:
    image: pgbouncer/pgbouncer
    network_mode: host
    environment:
      - DATABASES_HOST=localhost
      - DATABASES_PORT=5432
      - DATABASES_USER=admin
      - DATABASES_PASSWORD=123
      - DATABASES_DBNAME=rinha
      - DATABASES_POOL_SIZE=30
      - PGBOUNCER_MAX_CLIENT_CONN=30
      - PGBOUNCER_RESERVE_POOL_SIZE=30
      - PGBOUNCER_DEFAULT_POOL_SIZE=30
    depends_on:
      db:
        condition: service_healthy  

  app1: &app
    build:
      context: .
      args:
      - HTTP_PORT=3000
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "170MB"    

  app2:
    <<: *app
    build:
      context: .
      args:
      - HTTP_PORT=3001

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"