version: '3'

services:
  db:
    image: postgres:latest
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"

  app1: &app
    build: .
    environment: 
      - SERVER_NAME=:3000
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.39"
          memory: "170MB"    

  warmup:
    hostname: warmup
    container_name: warmup
    network_mode: host 
    image: fedora:39
    depends_on:
      db:
        condition: service_healthy
    command: |
      /bin/bash -c "echo 'warmuping'; sleep 5;
        for i in $(seq 1 50);
        do echo -n '.' ;
        curl -s -X GET http://localhost:9999/clientes/5/extrato > /dev/null  &
        curl -s -X POST -H 'Content-Type: application/json' -d '{\"valor\": 0, \"tipo\": \"d\", \"descricao\": \"warmupsh\"}' http:///localhost:3000/clientes/5/transacoes > /dev/null &
      done; echo 'warmup done';"
    deploy:
      resources: 
        limits:
          cpus: "0.02"
          memory: "16MB"        

  app2:
    <<: *app
    build: .
    environment: 
      - SERVER_NAME=:3001

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"